Cleaned up reverse reading, created setup.sh
Still need to make search functionality.

diff --git a/log b/log
--- a/log
+++ b/log
@@ -1,145 +1,87 @@
 #!/bin/bash
 #
-# CURRENTLY this is just a copy/paste of an old version of the `log` utility
-# I wrote @pid-1/utils/log. This will more or less be a cleaned up 'finalized'
-# version of that same script. Don't need to completely re-invent perfection.
-#
-# New(est) version of a my quick notetaking utility.  If I'm about to install
-# software, uninstall software, make changes to a config file, and want a place
-# to jot down what I've done. The previous version has been _invaluable_ to
-# recall a change I've made two weeks ago at 2am.
-#
-# It is important to have the text in a plaintext file, so output can be parsed
-# on the commandline if necessary. As well as using operations like grep to
-# quickly search.
+# changelog
+#  2021-05-30  :: Copied over from @pid-1/utils/log.sh
 
 #───────────────────────────────────( init )────────────────────────────────────
-trap cleanup EXIT
+source $(which hre-lib-import.sh) || exit 255
+.import --optional colors
 
-rst="\033[0m"     # Reset
-gr="\033[32m"     # Green
-rd="\033[31m"     # Red
-yl="\033[33m"     # Yellow
-bk="\033[30m"     # Black (dim)
-br="\033[37;1m"   # White (bright)
-
-cup="\033[1A"     # Cursor up 1 line
-cfw="\033[20C"    # Cursor forward 20 characters
-
-config_path="${HOME}/.config/hre-utils"
-data_file="${config_path}/logfile.txt"
+DATAFILE="${XDG_DATA_HOME:-$HOME/.local/share}/hre-utils/log/logfile.txt"
 
 #─────────────────────────────────( functions )─────────────────────────────────
-cleanup () {
-   printf "$rst"
-}
 
-usage () {
+function usage {
 cat << EOF
-USAGE: $(basename ${BASH_SOURCE[0]}) [--read <int:rows>] [--add]
-Run the utility. It opens 'vim' in insert mode. Type an entry to save to the
-logfile. Some minor processing is done before saving the line:
-   1. Newlines and lines beginning with a comment character (#) are stripped
-   2. Subsequent lines are intented +19 to properly justify beneath the date
-The data file should be easily human readable, and able to parse with common
-CLI tools (grep, sed).
+USAGE: ${bwh}$(basename ${BASH_SOURCE[0]})${rst} [--quick ENTRY] [--read NUM]
+
+Commands:
+   -h|--help            show this message and exit
+   -q|--quick ENTRY     adds entry on CLI without opening editor
+   -r|--read  NUM       displays last NUM entries
+
+Description:
+   Run \`log\`. A blank entry is opened in vim's insert mode. Type above the line
+   to save to a logfile. Minor processing is done:
+      1. Newlines and lines beginning with a comment character (#) are stripped
+      2. Subsequent lines are intented +19 to properly justify beneath the date
 EOF
+
 exit $?
 }
 
-
-setup () {
-   if [[ ! -d "${config_path}" ]]
-   then
-      printf "${yl}◆${rst} ${config_path} not found\n"
-      printf "   ${bk}└──${rst} Create? (Y/n) >> ${br}"
-
-      read ans ; printf "$rst"  #  <-- read response, reset color
-
-      if [[ $ans == '' ]] || [[ $ans =~ [Yy](es)? ]]
-      then
-         out="$(mkdir -p ${config_path})"
-         [[ $? -eq 0 ]] && {
-            printf "${cup}${cfw}${gr} Created${rst}\n"
-            sleep 0.5
-         } || {
-            printf "${cup}${cfw}${rd} ERROR${rst}\n"
-            printf "        ${bk}└──${rst} ${out}\n"
-            exit 1
-         }
-      else
-         printf "${cup}${cfw}${rd} Aborted${rst}\n"
-         exit 0
-      fi
+#────────────────────────────────────( i/o )────────────────────────────────────
+function read_entries {
+   local num=$1
+   if [[ ! ${num} =~ ^[0-9]+$ ]] ; then
+      echo "${rd}◆${rst} Invalid read value \"${br}${num}${rst}\". "
+      exit 2
    fi
 
-   [[ ! $(which vim 2>/dev/null) ]] && {
-      printf "${rd}◆${rst} vim not found in \$PATH. Fuck you.\n"
-      exit 1
-   }
-}
+   local -a forward_lines buffer
+   mapfile forward_lines < "$DATAFILE"
 
-#────────────────────────────────────( i/o )────────────────────────────────────
-read_entries () {
-   found_entries=$1
-   [[ ! ${found_entries} =~ ^[0-9]+$ ]] && {
-      printf "${rd}◆${rst} Invalid read value "${br}${found_entries}${rst}". "
-      printf "Must be int.\n"
-      exit 2
-   }
+   local -i idx=${#forward_lines[@]}
+   while [[ $idx -gt 0 ]] && [[ $num -gt 0 ]] ; do
+      ((idx--))
+      line="${forward_lines[$idx]}"
 
-   declare -a lines
-   readarray raw_lines < "$data_file"
-
-   len=${#raw_lines[@]}
-   while [[ ${len} -gt 0 ]] && [[ ${found_entries} -gt 0 ]] ; do
-      ((len=$len-1))
-      line="${raw_lines[$len]}"
-
-      # Continuation line
-      if [[ ${line} =~ ^\ {19}.* ]] ; then
-         lines+="${line}"
-         continue
-      else
-         lines+="${line}"
-         ((found_entries=$found_entries-1))
+      if [[ ! "${line}" =~ ^[[:space:]]+ ]] ; then
+         ((num--))
       fi
+
+      buffer+=( "$line" )
    done
 
-   # God is this an awful approach.
-   # Iterates backwards through the text file, adds to the end of an array, then
-   # reads backwards through the array... to get forwards output. That's genuine
-   # insanity. It's midnight. And this """works""". Time to turn in for tonight,
-   # can work on doing it correctly tomorrow.
-
-   mapfile -d $'\n' lines <<< "${lines[@]}"
-   len="${#lines[@]}"
-   while [[ $len -ge 0 ]] ; do
-      printf "${lines[$len]}"
-      ((len=$len-1))
+   local -i idx=$(( ${#buffer[@]} - 1 ))
+   while [[ $idx -ge 0 ]] ; do
+      echo -n "${buffer[$idx]}"
+      ((idx--))
    done
-
-   echo
-   # This is to fix a small spacing issue created by the dogshit approach of up
-   # above.
 }
 
 
-add_entry () {
-   tmp=$(mktemp --suffix=.txt)
+function add_entry {
+   local tmpfile=$(mktemp --suffix=.txt)
 
-   echo -e "\n#────────────────────────( logfile )─────────────────────────" >> ${tmp}
-   echo "# Write quick notes, in case you need to refer to them in the" >> ${tmp}
-   echo "# future. You are already in insert mode. Just start writing." >> ${tmp}
-   echo "# Comments, empty lines, and blank newlines will be stripped." >> ${tmp}
+   #────────────────────────────( write tmpfile )───────────────────────────────
+   cat <<EOF >"$tmpfile"
 
+#────────────────────────( logfile )─────────────────────────
+# Write quick notes, in case you need to refer to them in the
+# future. You are already in insert mode. Just start writing.
+# Comments, empty lines, and blank newlines will be stripped.
+EOF
+
+   #────────────────────────────( edit tmpfile )────────────────────────────────
    # the `|| exit` allows the user to `:cq` without the script continuing.
-   vim -c "norm! ggO" -c 'startinsert' -c 'set wrap tw=61 cc=62' ${tmp} || exit 1
+   vim -c "norm! ggO" -c 'startinsert' -c 'set wrap tw=61 cc=62' ${tmpfile} || exit 0
 
+   #────────────────────────────( parse tmpfile )───────────────────────────────
    today="$(date '+%Y/%b/%d %H:%M')"
    spacer="$(for i in {1..19} ; do printf ' ' ; done)"
 
-   readarray lines < ${tmp}
+   readarray lines < "$tmpfile"
    for idx in "${!lines[@]}" ; do
       line="${lines[$idx]}"
 
@@ -148,25 +90,25 @@ add_entry () {
       [[ "${line}" =~ ^\ *#.* ]] && continue
 
       if [[ $idx -eq 0 ]] ; then
-         printf "${today}  ${line}" >> ${data_file}
+         printf "${today}  ${line}" >> ${DATAFILE}
          continue
       else
-         printf "${spacer}${line//.*\n+$//}" >> ${data_file}
+         printf "${spacer}${line//.*\n+$//}" >> ${DATAFILE}
       fi
    done
 }
 
 
-# EDIT -- work on this next
-find_entries () {
+function find_entries {
    search_pattern="$@"
    echo "NYI"
    exit 1
 }
 
-quick_entry () {
+
+function quick_entry {
    declare -a result
-   readarray -d $'\n' entry < <(echo "$@" | tr -s ' ' | sed 's/ /\n/g' )
+   mapfile entry < <(echo "$@" | tr -s ' ' | sed 's/ /\n/g' )
 
    lineNR=0
    for word in "${entry[@]//$'\n'/}" ; do
@@ -177,13 +119,13 @@ quick_entry () {
       # Normal case: append word to line, don't prepend space if it's the
       # first word of the line
       then
-         [[ ${#result[$lineNR]} -eq 0 ]] && {
+         if [[ ${#result[$lineNR]} -eq 0 ]] ; then
             result[$lineNR]+="$word"
             #printf "${result[$lineNR]}\n"
-         } || {
+         else
             result[$lineNR]+=" $word"
             #printf "${result[$lineNR]}\n"
-         }
+         fi
       # Length limit reached--word wrap
       else
          ((lineNR=$lineNR+1))
@@ -198,40 +140,38 @@ quick_entry () {
       line="${result[$idx]}"
 
       if [[ $idx -eq 0 ]] ; then
-         printf "${today}  ${line}\n" >> ${data_file}
+         printf "${today}  ${line}\n" >> ${DATAFILE}
          continue
       elif [[ $idx -eq $((${#result[@]} - 1)) ]] ; then
-         printf "${spacer}${line}\n" >> ${data_file}
+         printf "${spacer}${line}\n" >> ${DATAFILE}
       else
-         printf "${spacer}${line}" >> ${data_file}
+         printf "${spacer}${line}" >> ${DATAFILE}
       fi
    done
 }
 
 
 #══════════════════════════════════╡ ENGAGE ╞═══════════════════════════════════
-setup
-
 case "$1" in
    -h|--help|help)
-      usage 0
-      ;;
+         usage 0
+         ;;
+
    -r|--read|read)
-      shift
-      read_entries "$1"
-      ;;
-   -a|--add|add)
-      shift
-      quick_entry "$@"
-      ;;
+         shift ; read_entries "$1"
+         ;;
+
+   -q|--quick|quick)
+         shift ; quick_entry "$@"
+         ;;
+
    -f|--find|find)
-      shift
-      find_entries "$@"
-      ;;
-   '')
-      add_entry
-      ;;
-   *)
-      usage 1
-   ;;
+         shift ; find_entries "$@"
+         ;;
+
+   '')   add_entry
+         ;;
+
+   *)    usage 1
+         ;;
 esac
